import PostData from "./post.js";

const incident = {
  path: "incident",
  data: [
    {
      id: "INC-2023-8901",
      timestamp: "03:15 PM",
      // cameraId: "CAM-N-112",
      cameraId: "69c97be24617432cabd65521",
      location: "Vibhavadi-Rangsit Rd, Exit 14, Bang Sue, Bangkok",
      vehicleType: "car-car",
      aiConfidence: 94.2,
      severity: "High",
      status: "Dispatched",
      modelPrecision: 91.5,
      reliabilityScore: 96.8,
      aiReasoning:
        "High-confidence multiple vehicle collision detected during morning rush hour. Two-vehicle frontal impact observed with significant deformation patterns consistent with high-speed collision.",
      condition: "Clear / Dry Road",
      lat: 13.8796,
      lng: 100.5547,
      coordinates: { x: 72, y: 28 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8902",
      timestamp: "04:42 PM",
      // cameraId: "CAM-E-045",
      cameraId: "69c97be24617432cabd65512",
      location: "Silom Rd / Surawong Intersection, Bang Rak, Bangkok",
      vehicleType: "car-bike",
      aiConfidence: 88.3,
      severity: "Critical",
      status: "Under Review",
      modelPrecision: 87.1,
      reliabilityScore: 92.4,
      aiReasoning:
        "Critical incident: motorcycle involved in collision with sedan at busy downtown intersection. Rider appears to have been thrown from vehicle. Immediate medical response required.",
      condition: "Clear / Dry Road",
      lat: 13.7244,
      lng: 100.5269,
      coordinates: { x: 52, y: 48 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8903",
      timestamp: "05:05 PM",
      // cameraId: "CAM-W-302",
      cameraId: "69c97be24617432cabd65521",
      location: "Charoen Nakhon Rd, Block 800, Khlong San, Thon Buri",
      vehicleType: "truck-car",
      aiConfidence: 76.4,
      severity: "Medium",
      status: "Auto-Detected",
      modelPrecision: 74.2,
      reliabilityScore: 80.1,
      aiReasoning:
        "Medium severity rear-end collision between heavy goods vehicle and passenger car. Truck braking detected 1.2 seconds before impact. Traffic obstruction likely.",
      condition: "Rainy",
      lat: 13.7284,
      lng: 100.4956,
      coordinates: { x: 31, y: 55 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8904",
      timestamp: "06:20 PM",
      // cameraId: "CAM-S-099",
      cameraId: "69c97be24617432cabd65518",
      location: "Rama II Rd, KM 12, Bang Khun Thian, Bangkok",
      vehicleType: "pedestrian involved",
      aiConfidence: 65.0,
      severity: "Critical",
      status: "SMS Confirmed",
      modelPrecision: 63.8,
      reliabilityScore: 88.5,
      aiReasoning:
        "Pedestrian struck by vehicle at designated crossing. Victim stationary post-impact. Multiple witness SMS reports corroborate AI detection. Emergency dispatch critical.",
      condition: "Night",
      lat: 13.6236,
      lng: 100.4847,
      coordinates: { x: 58, y: 78 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8905",
      timestamp: "07:01 PM",
      // cameraId: "CAM-C-010",
      cameraId: "69c97be24617432cabd6551b",
      location: "Bang Na Roundabout, Bang Na, Bangkok",
      vehicleType: "bike-bike",
      aiConfidence: 91.0,
      severity: "Low",
      status: "Auto-Detected",
      modelPrecision: 90.3,
      reliabilityScore: 91.7,
      aiReasoning:
        "Low-severity collision between two motorcycles at roundabout. Both riders appear ambulatory. Minor vehicle damage detected. Standard patrol dispatch recommended.",
      condition: "Clear / Dry Road",
      lat: 13.6614,
      lng: 100.5947,
      coordinates: { x: 50, y: 50 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8906",
      timestamp: "07:45 PM",
      // cameraId: "CAM-N-205",
      cameraId: "69c97be24617432cabd6552a",
      location: "Outer Ring Road / Hwy 9 Northbound, Lat Phrao, Bangkok",
      vehicleType: "car-car",
      aiConfidence: 45.2,
      severity: "Low",
      status: "False Alarm",
      modelPrecision: 44.8,
      reliabilityScore: 42.3,
      aiReasoning:
        "Low confidence detection — likely false positive. Vehicles appear to have performed an emergency stop due to road debris. No actual collision impact detected. Flagged for operator review.",
      condition: "Foggy",
      lat: 13.834,
      lng: 100.6503,
      coordinates: { x: 65, y: 22 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8907",
      timestamp: "08:10 PM",
      // cameraId: "CAM-E-112",
      cameraId: "69c97be24617432cabd65524",
      location: "Lat Krabang Industrial Estate Rd, Lat Krabang, Bangkok",
      vehicleType: "truck-car",
      aiConfidence: 96.5,
      severity: "High",
      status: "Under Review",
      modelPrecision: 95.2,
      reliabilityScore: 97.1,
      aiReasoning:
        "High-severity T-bone collision between heavy truck and passenger vehicle at industrial park junction. Significant structural damage to passenger car. Airbag deployment confirmed via frame analysis.",
      condition: "Night",
      lat: 13.7208,
      lng: 100.755,
      coordinates: { x: 78, y: 60 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8908",
      timestamp: "09:30 PM",
      // cameraId: "CAM-W-150",
      cameraId: "69c97be24617432cabd65527",
      location: "Bhumibol Bridge Access Ramp, Bang Kho Laem, Bangkok",
      vehicleType: "car-car",
      aiConfidence: 89.2,
      severity: "Medium",
      status: "Dispatched",
      modelPrecision: 88.0,
      reliabilityScore: 90.4,
      aiReasoning:
        "Medium severity sideswipe collision on bridge approach ramp. Both vehicles still mobile post-impact. Lane obstruction detected. Traffic diversion recommended.",
      condition: "Rainy",
      lat: 13.7042,
      lng: 100.525,
      coordinates: { x: 44, y: 62 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8909",
      timestamp: "10:05 AM",
      // cameraId: "CAM-CB-001",
      cameraId: "69c97be24617432cabd65533",
      location: "Phahonyothin Rd, Chatuchak Market Junction, Bangkok",
      vehicleType: "car-bike",
      aiConfidence: 92.4,
      severity: "High",
      status: "Dispatched",
      modelPrecision: 91.0,
      reliabilityScore: 93.8,
      aiReasoning:
        "High-confidence collision between sedan and motorcycle at busy market junction. Motorcycle rider ejected. Emergency services alerted immediately.",
      condition: "Clear / Dry Road",
      lat: 13.8025,
      lng: 100.5535,
      coordinates: { x: 58, y: 32 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8910",
      timestamp: "11:20 AM",
      // cameraId: "CAM-NE-330",
      cameraId: "69c97be24617432cabd65515",
      location: "Ramkhamhaeng Rd, Soi 24, Hua Mak, Bangkok",
      vehicleType: "truck-car",
      aiConfidence: 87.6,
      severity: "Critical",
      status: "Under Review",
      modelPrecision: 85.9,
      reliabilityScore: 88.2,
      aiReasoning:
        "Critical rear-end collision. Delivery truck struck stationary vehicle at red light. Significant front-end damage to passenger car. Passenger car occupant appears unresponsive.",
      condition: "Clear / Dry Road",
      lat: 13.7566,
      lng: 100.631,
      coordinates: { x: 83, y: 43 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8911",
      timestamp: "02:45 PM",
      // cameraId: "CAM-SE-201",
      cameraId: "69c97be24617432cabd65536",
      location: "Sukhumvit 77, On Nut BTS Station, Phra Khanong, Bangkok",
      vehicleType: "car-car",
      aiConfidence: 95.1,
      severity: "Medium",
      status: "SMS Confirmed",
      modelPrecision: 94.3,
      reliabilityScore: 96.0,
      aiReasoning:
        "Two-vehicle collision near BTS station exit. Vehicles blocking left lane causing downstream congestion. No visible injuries but significant traffic disruption observed.",
      condition: "Clear / Dry Road",
      lat: 13.702,
      lng: 100.602,
      coordinates: { x: 80, y: 63 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8912",
      timestamp: "05:50 PM",
      // cameraId: "CAM-N-205",
      cameraId: "69c97be24617432cabd6552a",
      location: "Don Mueang Tollway Southbound, Don Mueang, Bangkok",
      vehicleType: "car-car",
      aiConfidence: 78.3,
      severity: "Medium",
      status: "Auto-Detected",
      modelPrecision: 77.1,
      reliabilityScore: 80.5,
      aiReasoning:
        "Sideswipe collision detected on tollway during evening peak hour. Both vehicles pulled to hard shoulder. Minimal structural damage. Traffic flow marginally affected.",
      condition: "Clear / Dry Road",
      lat: 13.92,
      lng: 100.605,
      coordinates: { x: 82, y: 10 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
    {
      id: "INC-2023-8913",
      timestamp: "08:30 AM",
      // cameraId: "CAM-C-010",
      cameraId: "69c97be24617432cabd6551b",
      location: "Bang Na Expressway Tollgate, Bang Na, Bangkok",
      vehicleType: "bike-bike",
      aiConfidence: 83.9,
      severity: "Low",
      status: "Dispatched",
      modelPrecision: 82.4,
      reliabilityScore: 85.1,
      aiReasoning:
        "Two-motorcycle collision at expressway tollgate. Both riders mobile post-incident. Traffic queuing detected. Patrol unit dispatched for traffic management.",
      condition: "Rainy",
      lat: 13.6614,
      lng: 100.5947,
      coordinates: { x: 75, y: 73 },
      note: "Two sedan vehicles involved in rear-end collision near exit 14 ramp. Speed was likely a factor. One driver sustained minor injuries and was transported to Rajavithi Hospital. No pedestrian involvement. Road fully cleared by 08:42. Recommend increasing patrol frequency during morning rush hour on this stretch.",
    },
  ],
};

try {
  incident.data.map(async (data) => await PostData(incident.path, data));
  console.log("Incident data added!!");
} catch (error) {
  console.log(error);
}
